# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings for TECMAH株式会社
title: TECMAH株式会社
email: info@tecmah.com
description: >- # this means to ignore newlines until "baseurl:"
  TECMAH株式会社は、AI・データ活用・PdM/PM支援を行うスタートアップです。
  データドリブンな意思決定と効果的なプロダクトマネジメントで、
  企業のデジタル変革を支援しています。
baseurl: "/tecmah-hp"
url: "https://tecmah.github.io"
twitter_username: "infotecmah"
github_username: tecmah

# Encoding for proper Japanese character support
encoding: utf-8
lang: ja

# Company information
company:
  name: TECMAH株式会社
  name_en: TECMAH Inc.
  tagline: AI・データ活用・PdM/PM支援
  tagline_en: AI, Data Analytics & Product Management Support

# Build settings
remote_theme: andrewbanchich/forty-jekyll-theme
# remote_theme: zerostaticthemes/jekyll-serif-theme
# Custom theme modifications for Serif style with Forty hero elements
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-polyglot

# Language settings for bilingual support
languages: ["ja", "en"]
default_lang: "ja"
exclude_from_localization: ["javascript", "images", "css", "public"]

# Navigation menu
navigation:
  - title: ホーム
    title_en: Home
    url: /
    url_en: /en/
  - title: サービス
    title_en: Services
    url: /services/
    url_en: /en/services/
  - title: 実績
    title_en: Work
    url: /work/
    url_en: /en/work/
  - title: 会社概要
    title_en: About
    url: /about/
    url_en: /en/about/
  - title: ポリシー
    title_en: Policy
    url: /policy/
    url_en: /en/policy/
  - title: お問い合わせ
    title_en: Contact
    url: /contact/
    url_en: /en/contact/

# Forty theme specific settings
subtitle: AI・データ活用・PdM/PM支援を行うスタートアップ
image: assets/images/banner.jpg
name: TECMAH株式会社
copyright: TECMAH株式会社

# Custom assets
custom_css: assets/css/main.css

# CTA Configuration
cta:
  free_consultation:
    text: "無料相談"
    text_en: "Free Consultation"
    url: "/contact/"
    url_en: "/en/contact/"
    fixed_position: true

# Social media and contact
social:
  email: info@tecmah.com
  phone: ""
  address: 東京都

# Tiles for the landing page
tiles-source: pages
tiles-count: 6

# Case Studies (Anonymous examples) - Multilingual support
case_studies:
  - title:
      ja: "製造業A社様"
      en: "Manufacturing Company A"
    description:
      ja: "AI予測メンテナンスシステム導入により、設備稼働率を15%向上"
      en: "AI predictive maintenance system implementation increased equipment utilization by 15%"
    result:
      ja: "年間コスト削減効果: 2,000万円"
      en: "Annual cost reduction effect: $200,000"
  - title:
      ja: "EC事業B社様"
      en: "E-commerce Company B"
    description:
      ja: "データドリブンな商品開発プロセス構築で、新商品の成功率を3倍に"
      en: "Data-driven product development process increased new product success rate by 3x"
    result:
      ja: "売上向上効果: 前年比150%"
      en: "Sales improvement: 150% YoY"
  - title:
      ja: "SaaS事業C社様"
      en: "SaaS Company C"
    description:
      ja: "プロダクトマネジメント体制整備により、開発効率を40%改善"
      en: "Product management system establishment improved development efficiency by 40%"
    result:
      ja: "リリース頻度向上: 月2回→週1回"
      en: "Release frequency: Monthly → Weekly"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
