# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings for TECMAH株式会社
title: TECMAH株式会社
email: info@tecmah.com
description: >- # this means to ignore newlines until "baseurl:"
  TECMAH株式会社は、AI・データ活用・PdM/PM支援を行うスタートアップです。
  データドリブンな意思決定と生成AIを活用したプロダクト開発で、
  企業のデジタル変革を伴走支援します。
baseurl: "/tecmah-hp"
url: "https://tecmah.github.io"
twitter_username: "InfoTECMAH"
github_username: tecmah

# Encoding for proper Japanese character support
encoding: utf-8
lang: ja

# Company information
company:
  name: TECMAH株式会社
  name_en: TECMAH Inc.
  tagline: AI・データ活用・PdM/PM支援
  tagline_en: AI, Data Analytics & Product Management Support
  representative:
    ja: 松浦賢孝
    en: Yoshinori Matsuura
  representative_title:
    ja: 代表取締役
    en: Representative Director & CEO
  established: 2025
  headquarters:
    ja: 〒060-0062 北海道札幌市中央区南二条西5丁目31-1 RMBld.701
    en: RMBld.701, 31-1 Minami 2-jo Nishi 5-chome, Chuo-ku, Sapporo, Hokkaido 060-0062, Japan

# Build settings
remote_theme: CloudCannon/dante-jekyll-bookshop-template@main

permalink: pretty

logo: assets/images/logo/tecmah-logo.svg

branding:
  mobile: assets/images/logo/tecmah-mark.svg
  mobile_height: 36px
  mobile_width: 36px
  desktop: assets/images/logo/tecmah-logo.svg
  desktop_height: 40px
  desktop_width: 168px

home:
  limit_portfolio: 6

collections:
  portfolio:
    output: true
    sort_by: weight

defaults:
  - scope:
      path: ""
      type: "portfolio"
    values: {}

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-polyglot
  - jekyll-environment-variables

# Language settings for bilingual support
languages: ["ja", "en"]
default_lang: "ja"
exclude_from_localization: ["javascript", "images", "css", "public"]

# Serif theme specific settings
name: TECMAH株式会社
copyright: TECMAH株式会社

# CTA Configuration
cta:
  free_consultation:
    text: "無料相談"
    text_en: "Free Consultation"
    url: "/contact/"
    url_en: "/en/contact/"
    fixed_position: true

# Social media and contact
social:
  email: info@tecmah.com
  phone: "+81-70-8359-2530"
  address: 〒060-0062 北海道札幌市中央区南二条西5丁目31-1 RMBld.701
  address_en: RMBld.701, 31-1 Minami 2-jo Nishi 5-chome, Chuo-ku, Sapporo, Hokkaido 060-0062, Japan

# Case Studies (Anonymous examples) - Multilingual support
case_studies:
  - title:
      ja: "教育SaaS企業"
      en: "Education SaaS Company"
    description:
      ja: "生成AIと学習者データを活用したアダプティブ学習機能とダッシュボードを構築"
      en: "Built generative AI-powered adaptive learning features and teacher dashboards on learner data"
    result:
      ja: "学習継続率 +18%／運用ロードマップとダッシュボードを整備"
      en: "+18% retention uplift with operational roadmap and new dashboards"
  - title:
      ja: "製造業音声データ活用プロジェクト"
      en: "Manufacturing Audio Analytics Initiative"
    description:
      ja: "音声認識・感情解析モデルとデータパイプラインを整備し、異常検知を自動化"
      en: "Deployed speech and emotion analytics with pipelines to automate anomaly detection"
    result:
      ja: "一次判定時間を50%短縮／経営報告フローを標準化"
      en: "Cut first-response lead time by 50% and standardized executive reporting"
  - title:
      ja: "小売×生成AI新規事業"
      en: "Retail Generative AI New Venture"
    description:
      ja: "Azure OpenAIとRAG構成を活用したインタラクティブミラーのPoC〜パイロット導入を伴走"
      en: "Led PoC-to-pilot interactive mirror using Azure OpenAI and RAG architecture"
    result:
      ja: "3ヶ月でデモ導入完了／スケーラブルなクラウドアーキテクチャと運用手順を設計"
      en: "Delivered pilot in 3 months with scalable cloud architecture and operating playbooks"
  - title:
      ja: "生成AIスタートアップ支援"
      en: "Generative AI Startup Enablement"
    description:
      ja: "市場調査・PoC開発・KPI設計を通じて新規サービスの事業性検証を支援"
      en: "Supported market research, PoC builds, and KPI design to validate a new generative AI service"
    result:
      ja: "投資判断材料を整理／継続改善プロセスとプロダクトバックログを構築"
      en: "Provided investment-grade insights and a structured backlog with continuous improvement cadence"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
